export default {
  outbound: "OUTBOUND CONNECTIONS SUMMARY", // arrive
  ACParking: "A/C PARKING BAY",
  loadInfo: "PASSENGER LOAD INFORMATION",
  countMachine: "COUNTING MACHINE",
  card: "GATE / TRANSIT CARD",
  arrange: "TRANSPORTATION ARRANGEMENT",
  conInfo: "SHORT CONNECTING INFORMATION",
  inbound: "INBOUND CONNECTION SUMMARY", // depart
  limitedTag: "LIMITED RELEASE TAG",
  fragile: "FRAGILE TAG",
  envelope: "ENVELOPE FOR RESTRICTED ITEM",
  bus: "BUS RELEASE FORM FOR DRIVER",
  stkPax: "STICKERS FOR INTERNATIONAL PAX",
  stkFlight: "STICKERS FOR FLIGHT COMBINED"
};
