export default {
  to: "TO",
  from: "FROM",
  group: "GROUP",
  roster: "ROSTER",
  flightNo: "FLIGHT NO.",
  date: "DATE",
  ACregis: "A/C REGISTERATION",
  ACtype: "A/C TYPE",
  POO: "PORT OF ORIGIN",
  sta: "STA",
  eta: "ETA",
  ata: "ATA",
  baygate1: "BAY / GATE",
  disemark: "DISEMARKATION",
  TSsamePlane: "T/S SAME PLANE",
  ciq: "CIQ",
  TScardDist: "T/S CARD DISTRIBUTED",
  SQ: "S/P ONBOARD",
  gateOpened: "GATE OPENED",
  gateClosed: "GATE CLOSED",
  POD: "PORT OF DESTINATION",
  std: "STD",
  etd: "ETD",
  atd: "ATD",
  baygate2: "BAY / GATE",
  crew: "CREW ARR. GATE",
  inform: "INFORM BOARDING",
  start: "START BOARDING",
  complete: "COMPLETE BOARDING",
  joining: "JOINING",
  transfer: "TRANSFER",
  samePlaneReboard: "SAME PLANE REBOARD",
  iatci: "IATCI",
  ostci: "OSTCI",
  staff: "STAFF ASSIGNED",
  collected: "BOARDING PASS / IMM CARD / TICKET COLLECTED BY",
  boco: "BOCO BY",
  busCo: "BUS CO-ORDINATOR",
  staffStand: "STAFF STAND BY AT A/C SIDE",
  boardingAnnounced: "BOARDING ANNOUNCED BY",
  baggageBy: "BAGGAGE INTERCEPTED BY",
  baggageTotal: "TOTAL (PCS)",
  babyStrollerBy: "BABY STROLLER INTERCEPTED BY",
  babyStrollerTotal: "TOTAL (PCS)",
  restrictedItemBy: "RESTRICTED ITEM COLLECTED BY",
  restrictedItemTotal: "TOTAL (PCS)",
  docCheck: "DOCUMENT : CHECKED / MATCHED BY",
  byPrior: "BOARDING BY PRIORITY",
  byRows: "BOARDING BY ROWS",
  specialCase: "SPECIAL CASE ( ARR / DEP )",
  handledBy: "HANDLED BY",
  ko: "KO",
  koB: "KO-B",
  lcs: "LSC",
  gateLeader: "CSS / GATE LEADER",
  remark: "REMARK"
};
